//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_SideBarType
    {
        public Account_SideBarType()
        {
            this.Account_ControllerName = new HashSet<Account_ControllerName>();
        }
    
        public int Type { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Account_ControllerName> Account_ControllerName { get; set; }
    }
}
