//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Areas.Example.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Photos
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public string Title { get; set; }
        public int Priority { get; set; }
        public int EmployeeId { get; set; }
        public string Content { get; set; }
        public string Contetn2 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
